### PR TITLE
Basic systemd service file.

### PR DESCRIPTION
**Pull request by fourbytes**
Works with .yml config files. (`systemctl enable --now vpncloud@configname`)

### CODE REVIEW

**Comment by fourbytes** [comment]
Will make sure this is installed properly in the deb when systemd is available so maybe don't merge yet.

**Comment by dswd** [comment]
Ok great. Just tell me when it is ready for merge.

**Comment by dswd** [comment]
@fourbytes Can I merge this or do you still work on it?

**Comment by fourbytes** [comment]
I've been quite busy lately but will try finish this up this week, just need to make sure the systemd service is properly installed and packaged in the built .deb.

**Comment by dswd** [comment]
I implemented systemd support in the latest commit. Thanks for submitting this draft, it helped me implement it.

**Pull request closed without merging**
